alias ddu="mvn versions:display-dependency-updates"
alias dpu="mvn versions:display-plugin-updates"
alias pcheck="mvn parent-checker:check"
alias mci="mvn clean install"
alias mct="mvn clean test"
alias mcid="mvn clean install deploy"
alias mc="mvn clean"
alias m="mvn"